name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v4
#      - run: |
#          yarn install --immutable --immutable-cache --check-cache
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
